set(OpenBLAS64_VERSION "0.31.0") 
set(OpenBLAS64_LIBRARY_DIRS "${CMAKE_CURRENT_LIST_DIR}/lib") 
set(OpenBLAS64_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")
set(OpenBLAS64_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/libopenblas_haswellp-r0.3.21.dev.a") 

add_library(OpenBLAS64::OpenBLAS64 SHARED IMPORTED)

set_target_properties(OpenBLAS64::OpenBLAS64 PROPERTIES
	IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/lib/libopenblas_haswellp-r0.3.21.dev.a"
	INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/include"
)